### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BiteDasher**
I recently worked on a script that can semi-automatically update the ChromeOS image on a device. If it's not difficult for you, could you please update the README?

### CODE REVIEW

**Comment by sebanc** [comment]
Thanks ! It is a very interesting approach :)

As cros updates is very often down, maybe it would be safer to parse the below link for the recovery (and not to prompt the user for the recovery name):
https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.conf

Otherwise, I just need to find some time to test it before I add the link.

**Comment by BiteDasher** [comment]
> Thanks ! It is a very interesting approach :)
> 
> As cros updates is very often down, maybe it would be safer to parse the below link for the recovery (and not to prompt the user for the recovery name):
> https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.conf
> 
> Otherwise, I just need to find some time to test it before I add the link.
> 

Oh, and I did not know about the existence of this file.  I think today I'll try to do something with it, and replace with this part of the code with html. Thanks!)

**Comment by BiteDasher** [comment]
@sebanc I just rewrote the script using your advice and was able to update my system with it. Can you see if everything fits the requirements?

**Comment by BiteDasher** [comment]
@sebanc ping

**Comment by sebanc** [comment]
Sorry, I did not find the time to test the script yet, I think I will have the time to do it today.

**Comment by sebanc** [comment]
I just tried it and it works great :) I am going to update the readme.

If you have the time at some point, I would suggest a check to make sure there is enough disk space for the update (around 5GB free I guess).

**Comment by sebanc** [comment]
I made a general update of the readme and directly included the link to your repo

**Comment by BiteDasher** [comment]
> I just tried it and it works great :) I am going to update the readme.
> 
> If you have the time at some point, I would suggest a check to make sure there is enough disk space for the update (around 5GB free I guess).

Okay, I'll work on that today. Thanks :)

**Comment by BiteDasher** [comment]
Added a check for available disk space

**Comment by sebanc** [comment]
Wow, that was fast ! Thanks a lot :)

**Pull request closed without merging**
